apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: FOO-ns
  name: FOO
  labels:
    app: FOO
spec:
  replicas: 3
  selector:
    matchLabels:
      app: FOO
  template:
    metadata:
      labels:
        app: FOO
    spec:
      containers:
      - name: FOO
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: FOO-curl
        image: foo-curl-app:latest
        command: ["/bin/sh", "-c", "/app/execute_curls.sh"]
        env:
        - name: TARGET_URL
          value: "http://FOO-svc.FOO-ns.svc.cluster.local:3000"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: FOO
  namespace: FOO-ns
  name: FOO-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: FOO
  type: ClusterIP
